### ISSUE TITLE
解决训练数据存在脏数据的问题-按理中cpu模型报错

### ISSUE THREAD

**Issue by ljg-lixufeng** [PaddlePaddle/TrustAI#43]
AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'
Exception ignored in: <function _DataLoaderIterSingleProcess.__del__ at 0x7f94943fbb90>
Traceback (most recent call last):
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 339, in __del__
    self._try_shutdown_all()
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 324, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterSingleProcess' object has no attribute '_shutdown'

**Comment by zhangyimi** [comment]
麻烦补充一下详细信息，运行环境是什么，运行到哪一步报错
