### ISSUE TITLE
似乎版本依赖有问题

### ISSUE THREAD

**Issue by ShawnALiu** [PaddlePaddle/TrustAI#53]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/__init__.py", line 16, in <module>
    from .token_level import *
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/__init__.py", line 16, in <module>
    from .method import *
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/method/__init__.py", line 16, in <module>
    from .attention import AttentionInterpreter
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/method/attention.py", line 19, in <module>
    from .base_interpret import TokenInterpreter
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/method/base_interpret.py", line 19, in <module>
    from ..common import merge_subword_special_idx
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/common/__init__.py", line 17, in <module>
    from .predict_functions import *
  File "/usr/local/lib/python3.8/dist-packages/trustai/interpretation/token_level/common/predict_functions.py", line 19, in <module>
    from paddle.fluid import layers
ModuleNotFoundError: No module named 'paddle.fluid'
python-BaseException

文心一言这样说：
![image](https://github.com/PaddlePaddle/TrustAI/assets/45930473/55eb871d-0e61-47be-84da-88c6b9aa1a72)

**Comment by magicleo** [comment]
同问，现在这个库还维护吗？

**Comment by HalfCooler** [comment]
嘿，我搞了个PR，把fluid的代码全都迁移过来了.要是官方接受了的话，让他们来更新一下，然后去搞一下发布

**Comment by mikev4** [comment]
> 嘿，我搞了个PR，把fluid的代码全都迁移过来了.要是官方接受了的话，让他们来更新一下，然后去搞一下发布

他们是不是不更新了。我看你在pypi上发了个包

**Comment by HalfCooler** [comment]
> > 嘿，我搞了个PR，把fluid的代码全都迁移过来了.要是官方接受了的话，让他们来更新一下，然后去搞一下发布
> 
> 他们是不是不更新了。我看你在pypi上发了个包

嗨，我那个包也没全改，可能还有没迁移的。。你自己看看吧，反正我是不再用paddle了，这个库看样子是似了
